### ISSUE TITLE
Design submission logic update

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/legacy-sub-processor#3]
When a design submission comes in, we need to store the submissions as separate submissions. i.e. A single user can have more than 1 submission and all of them count separately - they are reviewed separately and can win prizes for each sub. This is different than dev.

I believe this is the current code that is handling design submission persistence.

https://github.com/appirio-tech/ap-submission-processor/blob/dev/service/src/main/java/com/appirio/submissionprocessor/processors/InformixPersistenceProcessor.java#L76

**Comment by cwdcwd** [comment]
how's the progress on this one @coderReview ?

**Comment by BadalZ** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Legacy Processor: Logic update for design submission](https://trello.com/c/zPGgl7QB/37-legacy-processor-logic-update-for-design-submission)
